package net.blancodev.pickem4me;

public enum NFLTeam {

    KANSAS_CITY_CHIEFS,
    TAMPA_BAY_BUCCANEERS,
    BUFFALO_BILLS,
    GREEN_BAY_PACKERS,
    LOS_ANGELES_RAMS,
    BALTIMORE_RAVENS,
    CLEVELAND_BROWNS,
    SEATTLE_SEAHAWKS,
    TENNESSEE_TITANS,
    SAN_FRANCISCO_49ERS,
    PITTSBURGH_STEELERS,
    DALLAS_COWBOYS,
    ARIZONA_CARDINALS,
    INDIANAPOLIS_COLTS,
    LOS_ANGELES_CHARGERS,
    MIAMI_DOLPHINS,
    NEW_ENGLAND_PATRIOTS,
    MINNESOTA_VIKINGS,
    NEW_ORLEANS_SAINTS,
    WASHINGTON_FOOTBALL_TEAM,
    LAS_VEGAS_RAIDERS,
    CHICAGO_BEARS,
    ATLANTA_FALCONS,
    NEW_YORK_GIANTS,
    CAROLINA_PANTHERS,
    DENVER_BRONCOS,
    PHILADELPHIA_EAGLES,
    CINCINNATI_BENGALS,
    JACKSONVILLE_JAGUARS,
    NEW_YORK_JETS,
    DETROIT_LIONS,
    HOUSTON_TEXANS;

    public int getPowerRanking() {
        return ordinal();
    }

}
